#服务配置
server:
  port: 1993
  tomcat:
    uri-encoding: UTF-8
  error:
    path: /error
spring:
    #数据配置
  datasource:
    url: jdbc:mysql://localhost:3306/db_demo_kms?characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      auto-commit: false
      connection-timeout: 30000
      idle-timeout: 25000
      login-timeout: 5
      max-lifetime: 30000
      read-only: false
      validation-timeout: 3000
      maximum-pool-size: 15
      minimum-idle: 10
      data-source-properties:
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      useServerPrepStmts: true
      useLocalSessionState: true
      rewriteBatchedStatements: true
      cacheResultSetMetadata: true
      cacheServerConfiguration: true
      elideSetAutoCommits: true
      maintainTimeStats: false
      #静态文件
  mvc:
    throw-exception-if-no-handler-found: true
#    static-path-pattern: /static/**
    favicon:
      enabled: true
    servlet:
      path: /
  thymeleaf:
    check-template: false
    cache: false
    suffix: .html
    prefix: classpath:/static/html/
    mode: HTML5
    enabled: true
    check-template-location: true
    encoding: UTF-8
  resoursces:
    static-locations: classpath:/resources/,classpath:/static/,classpath:/static/css/,classpath:/static/js/
 #启动对@AspectJ注解的支持
  aop:
    proxy-target-class: true
#  jackson:
#    mapper: true
jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
#mybatis插件
mybatis-plus:
  mapper-locations: classpath:com/example/demo/dao/mapper/*Mapper.xml
  type-aliases-package: com.example.demo.entity
  executor-type: reuse
  configuration:
    map-underscore-to-camel-case: false
    cache-enabled: false
#      global-config:
#        db-config:
#          field-strategy: not_empty
#          id-type: auto
#          db-type: mysql
#          table-underline: true
#          column-underline: true
#          banner: false
#          refresh: true
#mybatis:
#  mapper-locations: classpath:com/example/demo/dao/mapper/*Mapper.xml
#  type-aliases-package: com.example.demo.entity
#  executor-type: reuse
#  configuration:
#    map-underscore-to-camel-case: false
#    cache-enabled: false
#分页插件插件配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
debug: true
logging.level.org.springframework.boot.autoconfigure: ERROR
trace: false

